@startuml

MCU -> Bootloader: reset
activate Bootloader
Bootloader -> Bootloader: Recover? (yes)
Bootloader -> Bootloader: Restore previous firmware
note left: Copy the previous firmware from secondary to primary slot
Bootloader -> Application: Jump to primary slot
deactivate Bootloader

activate Application
note right: This is the previous version\nof the firmware
Application -> Application: Normal Operation
Application -> MCU: Reset
deactivate Application

@enduml