#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace Pinetime {
  namespace Applications {
    namespace Localization {

      enum class Language : uint8_t { English, Spanish, Portuguese, Russian, French, German, Italian, Turkish, Polish, Catalan, Basque, Count };

      enum class StringId : uint8_t {
        Empty,
        Settings,
        Display,
        WakeUp,
        TimeFormat,
        WatchFace,
        Steps,
        HeartRate,
        DateTime,
        Weather,
        Battery,
        Chimes,
        ShakeCalibration,
        Firmware,
        Ota,
        Bluetooth,
        About,
        Language,
        English,
        Spanish,
        Portuguese,
        Russian,
        French,
        German,
        Italian,
        Turkish,
        Polish,
        Catalan,
        Basque,
        Back,
        On,
        Off,
        Enabled,
        Disabled,
        Start,
        Stop,
        Pause,
        Reset,
        Set,
        Charging,
        FullyCharged,
        Discharging,
        BatteryLow,
        BatteryCritical,
        ReadingBattery,
        Volts,
        DailyStepsGoal,
        Goal,
        Trip,
        Yesterday,
        HeartRateBpm,
        NotEnoughData,
        NoTouchDetected,
        Measuring,
        Stopped,
        BackgroundInterval,
        Continuous,
        DisplayTimeout,
        AlwaysOn,
        SingleTap,
        DoubleTap,
        RaiseWrist,
        ShakeWake,
        LowerWrist,
        SetCurrentTime,
        SetCurrentDate,
        Metric,
        Imperial,
        EveryHour,
        Every30Minutes,
        TillReboot,
        FirmwareAndFiles,
        ClearSky,
        FewClouds,
        ScatteredClouds,
        BrokenClouds,
        ShowerRain,
        Rain,
        Thunderstorm,
        Snow,
        Mist,
        Clear,
        Cloudy,
        Showers,
        Thunder,
        Notification,
        IncomingCallFrom,
        Notifications,
        NoNotifications,
        TooLarge,
        ZeroDivision,
        Warning,
        TouchControllerError,
        WarrantyTip,
        Proceed,
        Version,
        ShortRef,
        FirmwareValidated,
        FirmwareRollbackWarning,
        Validate,
        Rollback,
        FirmwareUpdate,
        Waiting,
        WakeSensitivity,
        Calibrate,
        Shake,
        Ready,
        Connected,
        Disconnected,
        ImageOk,
        Error,
        YouHaveMail,
        Navigation,
        Score,
        AlarmNotSet,
        TimeToAlarm,
        Days,
        Hours,
        Minutes,
        Seconds,
        Once,
        Daily,
        Weekdays,
        Heads,
        Tails,
        Count
      };

      static constexpr size_t LanguageCount = static_cast<size_t>(Language::Count);
      static constexpr size_t StringCount = static_cast<size_t>(StringId::Count);

      const char* Translate(Language language, StringId id);

    }
  }
}
