@startuml

MCU -> Bootloader: reset
activate Bootloader
Bootloader -> Bootloader: Recover? (no)
Bootloader -> Bootloader: New version? (no)
Bootloader -> Application: Jump to primary slot
deactivate Bootloader

activate Application
note right: This is the current version of the firmware
Application -> Application: OTA procedure
note right: Download a new firmware version and\n store it in secondary slot
Application -> MCU: Reset
deactivate Application



@enduml