blank_issues_enabled: true
contact_links:
  - name: PineTime community chat (Matrix)
    url: https://app.element.io/#/room/#pinetime:matrix.org
    about: Please ask questions about PineTime here.
  - name: PineTime developers chat (Matrix)
    url: https://app.element.io/#/room/#pinetime-dev:matrix.org
    about: Please ask questions about PineTime development here.
