name: Feature Request
description: File a feature request
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking the time to fill out this feature request!**
        *Please, before opening a feature request, check if similar issues already exist. In that case, use those issues to provide your feedback instead.*
  - type: checkboxes
    attributes:
      options:
      - label: I searched for similar feature request and found none was relevant.
        required: true
  - type: markdown
    attributes:
      value: |
        **Note:** keep in mind that, while InfiniTime is usable, it is still under heavy development and as such it is continuously evolving.
        Some features you want to see implemented might not be compatible with the current state of the project, or might not even be suitable to include *in the firmware* of the watch.
  - type: input
    id: desc-brief
    attributes:
      label: Pitch us your idea!
      description: A one-line elevator pitch of the feature you'd like to see implemented.
      placeholder: "Ex. My dog wants InfiniTime on its smart collar."
    validations:
      required: true
  - type: textarea
    id: desc-long
    attributes:
      label: Description
      description: |
        Give us a detailed description of the feature you are proposing. Mockups or a description of the possible use cases are highly appreciated.
        Tell us why this should be included in the firmware.
      placeholder: "Ex. Here is a drawing of my dog wearing an InfiniTime collar and smiling."
  - type: markdown
    id: companion-app
    attributes:
      value: |
        If this requires features missing from other software (for example a companion app), please take care of opening any relevant feature request over there as well.
