name: Feature Request
description: File a feature request
labels: ["feature request"]
body:
  - type: checkboxes
    attributes:
      label: Verification
      options:
      - label: I searched for similar issues and found none was relevant.
        required: true
      - label: This feature is **not** related to a problem. If this feature relates to a problem, use the issue report form instead.
        required: true
  - type: input
    id: desc-brief
    attributes:
      label: Pitch us your idea!
      description: A one-line elevator pitch of the feature you'd like to see implemented.
      placeholder: "Ex. My dog wants InfiniTime on its smart collar."
    validations:
      required: true
  - type: textarea
    id: desc-long
    attributes:
      label: Description
      description: |
        Give us a detailed description of the feature you are proposing. Mockups or a description of the possible use cases are highly appreciated.
        Tell us why this should be included in the firmware.
      placeholder: "Ex. Here is a drawing of my dog wearing an InfiniTime collar and smiling."
  - type: markdown
    id: companion-app
    attributes:
      value: |
        If this requires features missing from other software (for example a companion app), please take care of opening any relevant feature request over there as well.
