#pragma once

// Do not edit this file, it is automatically generated by CMAKE!

#include <cstdint>

namespace Pinetime {
  class Version {
    public:
      static constexpr uint32_t Major() {return major;}
      static constexpr uint32_t Minor() {return minor;}
      static constexpr uint32_t Patch() {return patch;}
      static constexpr const char* GitCommitHash() {return commitHash;}
      static constexpr const char* VersionString() {return versionString;}
    private:
      static constexpr uint32_t major = 1;
      static constexpr uint32_t minor = 15;
      static constexpr uint32_t patch = 0;
      static constexpr const char* commitHash = "ce2dd719";
      static constexpr const char* versionString = "1.15.0";
  };
}
