#pragma once

// Do not edit this file, it is automatically generated by CMAKE!

#include <cstdint>

namespace Pinetime {
  namespace Version {
      const char* GitCommitDate();
      const char* GitCommitTime();
  };
}
