name: Build firmware (Guardian Beacon)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - guardian-beacon
    paths-ignore:
      - ".github/workflows/docker.yml"
      - "README.md"

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Mark repo as safe
        run: git config --global --add safe.directory "${{ github.workspace }}"

      - name: Docker login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin"

      - name: Build with our Docker image
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" ghcr.io/${{ github.repository_owner }}/guardian-beacon:latest /bin/bash -lc '
            set -eux
            cd /src
            echo "== Building firmware inside container =="

            # Te ścieżki są osadzone w obrazie
            export ARM_NONE_EABI_TOOLCHAIN_PATH="$ARM_NONE_EABI_TOOLCHAIN_PATH"
            export NRF5_SDK_PATH="$NRF5_SDK_PATH"

            if [ -f scripts/build.sh ]; then
              ./scripts/build.sh -t pinetime -r
            else
              cmake -S . -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DARM_NONE_EABI_TOOLCHAIN_PATH="$ARM_NONE_EABI_TOOLCHAIN_PATH" \
                -DNRF5_SDK_PATH="$NRF5_SDK_PATH" \
                -DBUILD_DFU=1 -DBUILD_RESOURCES=1
              cmake --build build -j"$(nproc)"
            fi

            echo "== Build complete =="
            ls -lh build || true
            ls -lh build/*.bin build/*.hex build/*.zip 2>/dev/null || true
          '

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: guardian-firmware
          path: |
            build/*.bin
            build/*.hex
            build/*.zip
            build/*.out
          if-no-files-found: warn
