name: Build (no Docker required)

on:
  push:
    branches: [ main, master, guardian-beacon ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive   # jeśli masz submoduły, to je pobierze

      # --- [OPCJONALNE] Logowanie do Docker Hub – odpali się tylko gdy są sekrety ---
      - name: Log in to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Tu daj swoje kroki budowania (jeśli jeszcze nie mamy SDK, to na razie pomijamy)
      - name: Print repo tree (diagnostic)
        run: |
          echo "Repo content:"
          ls -la
          echo
          echo "If you want to build firmware, we will add SDK step later."

      # --- [OPCJONALNE] Build and push Docker image – też odpali się tylko z sekretami ---
      - name: Build & Push Docker image (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/guardian-beacon:latest
