name: Build & Push Docker image (GHCR)

on:
  push:
    branches:
      - main
      - guardian-beacon
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare lowercase owner
        id: prep
        run: |
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push (GHCR)
        run: |
          IMAGE="ghcr.io/${{ steps.prep.outputs.owner_lc }}/guardian-beacon:latest"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
